apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vvmvgvt17-python
  janus-idp.io/tekton: vvmvgvt17-python
  backstage.io/kubernetes-id: vvmvgvt17-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vvmvgvt17-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
